version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.18

    commands:
      # Download and install TerraForm 
      - wget https://releases.hashicorp.com/terraform/0.12.31/terraform_0.12.31_linux_amd64.zip
      - unzip terraform_0.12.31_linux_amd64.zip -d /usr/bin/

  pre_build:
    commands:
      # Download original DCE(TM) project from GitHub
      - git clone --depth 1 --branch v0.34.1 https://github.com/Optum/dce.git

      # Update/overwrite some files with "Sandbox Accounts for Events"-specific versions:
      # Let AWS Nuke ignore/skip deletion of OrganizationAccountAccess role
      - cp dce-integration/cmd/codebuild/reset/default-nuke-config-template.yml dce/cmd/codebuild/reset/default-nuke-config-template.yml

      # Use customized buildspec file for AWS Nuke that includes pre-, fix- and post-build scripts to catch some edge cases & copy scripts
      - cp dce-integration/cmd/codebuild/reset/buildspec.yml dce/cmd/codebuild/reset/buildspec.yml
      - cp dce-integration/cmd/codebuild/reset/pre-cleanup.sh dce/cmd/codebuild/reset/pre-cleanup.sh
      - cp dce-integration/cmd/codebuild/reset/fix-cleanup.sh dce/cmd/codebuild/reset/fix-cleanup.sh
      - cp dce-integration/cmd/codebuild/reset/post-cleanup.sh dce/cmd/codebuild/reset/post-cleanup.sh

      # Set "Sandbox Accounts for Events"-specific config for TerraForm variables
      - cp dce-integration/modules/dce.tfvars dce/modules/

      # Use improved TerraForm file for DynamoDB deployment to allow on-demand instead of provisioned capacity
      - cp dce-integration/modules/dynamodb.tf dce/modules/dynamodb.tf

      # Use improved build script that includes pre-, fix- and post-build scripts into AWS Nuke build artifact 
      - cp dce-integration/scripts/build.sh dce/scripts/build.sh

      # Use improved IAM policy template for principal to avoid conflicts between policy and SCPs 
      - cp dce-integration/modules/fixtures/policies/principal_policy.tmpl dce/modules/fixtures/policies/principal_policy.tmpl

      # Replace Go1.x Lambda runtime (deprecated) with AmazonLinux2
      - sed -i 's/"go1.x"/"provided.al2"/g' dce/modules/lambda/lambda.tf
      - sed -i 's/= var.handler/= "bootstrap"/g' dce/modules/lambda/lambda.tf
      - sed -i 's|go build -v -o ../../../bin/lambda/$mod_name$|go build -v -o ../../../bin/lambda/bootstrap|g' dce/scripts/build.sh
      - sed -i 's|^\s*bin/lambda/$mod_name$|      bin/lambda/bootstrap|g' dce/scripts/build.sh

  build:
    commands:
      # Build and deploy backend resources via TerraForm
      - chmod +x dce-integration/scripts/terraform-deploy.sh
      - cd dce/modules
      - ../../dce-integration/scripts/terraform-deploy.sh

      # Build & deploy code artifacts
      - cd ..
      - make deploy
